### ISSUE TITLE
Unable to set up backend

### ISSUE THREAD

**Issue by kumararoosh** [yaretzj/ChoreCenter#67]
Hi all,
I am one of your peer-reviewers, and I am trying to set up the backend Flask environment, however this step is confusing me:

> Use the command . venv/bin/activate on Mac or . venv/Scripts/activate on Windows to activate the virtual environment. You can deactivate the virtual environment with the command deactivate when you are done using the application.

All of the previous steps have worked for me, but this command does not make sense to me. I would love some clarification!

Thanks!

**Comment by dishadc** [comment]
@kumararoosh  Were you able to create the virtual environment with the command `python3 -m venv venv` ? 
If you were able to do this you should be able to run the command `. venv/bin/activate` to activate the virtual environment. 
Also note this should be done in the `Backend` directory

**Comment by kumararoosh** [comment]
I was able to run that command, but it returned me back to the command line, and it does not allow me to run `. venv/bin/activate`

**Comment by dishadc** [comment]
are you on mac or windows ?

**Comment by kumararoosh** [comment]
I am on windows

**Comment by dishadc** [comment]
then you need to use the command `. venv/Scripts/activate` as mentioned in the instructions

**Comment by dishadc** [comment]
if you are unable to run the command mentioned in the previous comment, navigate to the `venv/Scripts` directory and run the command `activate` from there. Then navigate back to the `Backend` directory and continue with the setup.

**Comment by kumararoosh** [comment]
ok that worked thank you!

**Comment by dishadc** [comment]
np, closing this issue now
